apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kafka
  labels:
    app: infra-devops
    component: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-devops
      component: kafka
  template:
    metadata:
      labels:
        app: infra-devops
        component: kafka
    spec:
      containers:
        - env:
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_BROKER_ID
              value: "1"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper-service:2181
            - name: KAFKA_CREATE_TOPICS
              value: "test-topic:1:1"
          image: wurstmeister/kafka
          imagePullPolicy: IfNotPresent
          name: kafka
          ports:
            - containerPort: 9092
