apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: infra-devops
    component: kafka
spec:
  type: NodePort
  ports:
    - name: kafka-port
      port: 9092
      nodePort: 30092
      targetPort: 9092
  selector:
    app: infra-devops
    component: kafka
