apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
  labels:
    app: infra-devops
    component: zookeeper
spec:
  type: NodePort
  ports:
    - name: zookeeper-port
      port: 2181
      nodePort: 30181
      targetPort: 2181
  selector:
    app: infra-devops
    component: zookeeper
