apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: infra-devops
    component: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: infra-devops
      component: zookeeper
  template:
    metadata:
      name: zookeeper
      labels:
        app: infra-devops
        component: zookeeper
    spec:
      containers:
        - image: wurstmeister/zookeeper
          imagePullPolicy: IfNotPresent
          name: zookeeper
          ports:
            - containerPort: 2181
