---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  labels:
    app: infra-devops
    component: postgres
spec:
  ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    app: infra-devops
    component: postgres
